select * from SAP_BTP_AI_MESSAGETIMEAGGREGATES 
select * from SAP_BTP_AI_MESSAGES 

select * from SAP_BTP_AI_SITUATIONS

SELECT * FROM SAP_BTP_AI_ASSESSMENTS


select CREATIONTSTAMP,count(*) from SAP_BTP_AI_MESSAGES GROUP BY CREATIONTSTAMP

SELECT TO_VARCHAR(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS.FF7') FROM DUMMY;
