"""Centralized catalog paths, column names, table names, and thresholds."""

from pathlib import Path

# ── Project root ──────────────────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parents[3]
API_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = API_ROOT / "output"
CATALOG_DIR = Path(__file__).resolve().parent / "catalogs"

# Sheet names
SHEET_RESIDENTIAL = "Residential"
SHEET_RESIDENTIAL_SEGMENT = "Residential_Residential_Segment"
SHEET_COMMERCIAL = "Commercial"
SHEET_COMMERCIAL_SEGMENT = "Commercial_Residential_Segment"
SHEET_RATE_COUNT = "Cnt of BILACCT_K for rate"
SHEET_ACTIVE_OFFERING = "Active business offering"

PROGRAM_CODES_SHEET_CONTRACT = "Program Contract"
PROGRAM_CODES_SHEET_SAMPLES = "Sample Accounts"

# ── Column names (Residential / Commercial shared) ────────────────────────
COL_BILLING_ACCOUNT = "BILLING ACCOUNT#"
COL_STATUS = "STATUS"
COL_RATE_PLAN = "RATE PLAN"
COL_PAYMENT_PLAN = "PAYMENT PLAN CODE"
COL_CREDIT_RATING = "CREDIT RATING CODE"
COL_COUNTY = "COUNTY CODE"
COL_BILL_LANGUAGE = "PREFERRED BILL LANGUAGE"
COL_METER_USAGE = "METER READ USAGE QUANTITY"
COL_BILL_PAID = "BILL PAID AMOUNT"
COL_BILL_TOTAL = "BILL TOTAL AMOUNT"
COL_READ_DATE = "READ DATE"
COL_ON_PEAK = "ON-PEAK ENERGY USAGE"
COL_OFF_PEAK = "OFF-PEAK ENERGY USAGE"
COL_OTHER_PROGRAMS = "OTHER PROGRAMS"

# Commercial-only columns
COL_NAIC_CODE = "NAIC CODE"
COL_INDUSTRY = "INDUSTRY"

# Segment sheets
COL_SEGMENT_NUM = "SEGMENT #"
COL_SEGMENT_NAME = "SEGMENT NAME"
# Commercial segment sheet uses different column names
COL_COMM_BILLING_ACCOUNT = "BILACCT_K"
COL_COMM_SEGMENT = "SEGMENT"
COL_COMM_SEGMENT_NAME = "SEGMENT NAME"

# Active business offering
COL_BIZ_OFFERING_CODE = "BUSINESS OFFERING CODE"
COL_BIZ_OFFERING_NAME = "BUSINESS OFFERING NAME"
COL_CUSTOMER_TYPE = "CUSTOMER TYPE"

# Program Contract sheet (row 2 is the real header)
COL_PC_PROGRAM = "Program/Contract"
COL_PC_SCREEN_NAME = "Screen Name"
COL_PC_SERVICE_OPTION = "Service Option Name or Contract Type Code"
COL_PC_SERVICE_TYPE = "Service Option Type"
COL_PC_PROGRAM_OR_CONTRACT = "Program or Contract"

# ── Tuneable thresholds ───────────────────────────────────────────────────
HIGH_USAGE_PERCENTILE = 75          # F11 -- accounts above this %ile are "high usage"
SHORTFALL_HISTORY_THRESHOLD = 2     # F10 -- periods with shortfall out of last 6
BILL_INCREASE_THRESHOLD = 0.0       # F12 -- any YoY increase triggers the flag
TREND_RISE_FACTOR = 1.10            # F11 -- 110% = rising usage detection
USAGE_AVERAGE_PERIODS = 3           # L9 / F6-F8 -- number of recent bills to average
ANNUAL_USAGE_SMALL_BUSINESS_MAX = 300_000
DEMAND_RESPONSE_USAGE_THRESHOLD = 120_000

# ── HANA runtime table names ──────────────────────────────────────────────
TABLE_RESIDENTIAL = "COA_RESIDENTIAL"
TABLE_RESIDENTIAL_SEGMENT = "COA_RESIDENTIAL_SEGMENT"
TABLE_COMMERCIAL = "COA_COMMERCIAL"
TABLE_COMMERCIAL_SEGMENT = "COA_COMMERCIAL_SEGMENT"
TABLE_ACTIVE_OFFERING = "COA_ACTIVE_OFFERING"
TABLE_PROGRAM_CONTRACT = "COA_PROGRAM_CONTRACT"
TABLE_PROGRAM_SAMPLES = "COA_PROGRAM_SAMPLES"
TABLE_ACCOUNT_PROFILE = "COA_ACCOUNT_PROFILE"
TABLE_DER_PROFILE = "COA_DER_PROFILE"
TABLE_PROGRAM_EVENT_HISTORY = "COA_PROGRAM_EVENT_HISTORY"
TABLE_SAVED_CUSTOMER_ANSWERS = "COA_SAVED_CUSTOMER_ANSWERS"

LLM_MODEL = "gpt-4.1"
LLM_TEMPERATURE = 0.2
LLM_MAX_TOKENS = 2000
PROGRAM_CATALOG_FILE = CATALOG_DIR / "program_catalog.json"
PROGRAM_RULE_MATRIX_FILE = CATALOG_DIR / "program_rule_matrix.json"
TARIFF_CATALOG_FILE = CATALOG_DIR / "tariff_catalog.json"
COMMERCIAL_TAXONOMY_FILE = CATALOG_DIR / "commercial_taxonomy.json"
CLAUSE_EXTRACTION_CACHE_FILE = OUTPUT_DIR / "program_clause_candidates.json"

# ── New HANA-backed profile/history columns ──────────────────────────────
COL_PROFILE_DWELLING_TYPE = "DWELLING TYPE"
COL_PROFILE_SERVICE_ENTRANCE_AMPS = "SERVICE ENTRANCE AMPS"
COL_PROFILE_SERVICE_START_DATE = "SERVICE START DATE"
COL_PROFILE_OWNERSHIP_STATUS = "OWNERSHIP STATUS"
COL_PROFILE_OCCUPANCY_STATUS = "OCCUPANCY STATUS"
COL_PROFILE_COOLING_SYSTEM_TYPE = "COOLING SYSTEM TYPE"
COL_PROFILE_CENTRAL_AC = "CENTRAL AC"
COL_PROFILE_NEW_CONSTRUCTION = "NEW CONSTRUCTION FLAG"
COL_PROFILE_CONNECTED_UNIT_COUNT = "CONNECTED UNIT COUNT"
COL_PROFILE_PROJECT_STAGE = "PROJECT STAGE"
COL_PROFILE_CONDITIONED_SQFT = "CONDITIONED SQFT"
COL_PROFILE_ACCOUNT_GOOD_STANDING = "ACCOUNT GOOD STANDING"
COL_PROFILE_ACCOUNT_NAME_TYPE = "ACCOUNT NAME TYPE"
COL_PROFILE_SAME_ACCOUNT_HOLDER_12M = "SAME ACCOUNT HOLDER 12M"
COL_PROFILE_QUALIFIED_PRICE_PLAN = "QUALIFIED PRICE PLAN"
COL_PROFILE_LARGE_ENERGY_CONSUMER = "LARGE ENERGY CONSUMER"
COL_PROFILE_CURTAILMENT_CAPABILITY = "CURTAILMENT CAPABILITY"
COL_PROFILE_ELIGIBLE_CONTRACTOR = "ELIGIBLE CONTRACTOR"
COL_PROFILE_PROJECT_EXCEEDS_BASELINE_10 = "PROJECT EXCEEDS BASELINE 10"
COL_PROFILE_ENERGY_STAR_MFNC = "ENERGY STAR MFNC"

COL_DER_SOLAR_OWNERSHIP = "SOLAR OWNERSHIP"
COL_DER_NEW_ROOFTOP_SOLAR = "NEW ROOFTOP SOLAR"
COL_DER_QUALIFYING_FACILITY_KW_AC = "QUALIFYING FACILITY KW AC"
COL_DER_STORAGE_ONLY = "STORAGE ONLY FLAG"
COL_DER_REC_RIGHTS_OWNED = "REC RIGHTS OWNED"
COL_DER_PRIOR_REC_ASSIGNMENT = "PRIOR REC ASSIGNMENT ACTIVE"
COL_DER_PREFERRED_SOLAR_INSTALLER = "PREFERRED SOLAR INSTALLER"
COL_DER_THERMOSTAT_BRAND = "THERMOSTAT BRAND"
COL_DER_THERMOSTAT_PROVIDER_ACCOUNT = "THERMOSTAT PROVIDER ACCOUNT"
COL_DER_THERMOSTAT_WIFI = "THERMOSTAT WIFI CONNECTED"
COL_DER_ELIGIBLE_CONNECTED_DEVICE = "ELIGIBLE CONNECTED DEVICE"
COL_DER_SMART_THERMOSTAT_PURCHASE = "SMART THERMOSTAT PURCHASE ELIGIBLE"
COL_DER_EV_CHARGER_BRAND = "EV CHARGER BRAND"
COL_DER_ELIGIBLE_HOME_EV_CHARGER = "ELIGIBLE HOME EV CHARGER"
COL_DER_BATTERY_OWNERSHIP = "BATTERY OWNERSHIP"
COL_DER_BATTERY_PARTNER_BRAND = "BATTERY PARTNER BRAND"
COL_DER_COMPATIBLE_BATTERY = "COMPATIBLE BATTERY CONFIGURATION"
COL_DER_DEMAND_MGMT_INCLUDED = "DEMAND MANAGEMENT INCLUDED"

COL_EVENT_DATE = "EVENT DATE"
COL_EVENT_PROGRAM_ID = "PROGRAM ID"
COL_EVENT_PROGRAM_CODE = "PROGRAM CODE"
COL_EVENT_TYPE = "EVENT TYPE"

DECLINE_SUPPRESSION_DAYS = 90
