from __future__ import annotations

import asyncio
from pathlib import Path
from types import SimpleNamespace

from app import main as main_module
from app.services.metal_composition.config import MetalCompositionSettings


class FakeClassificationWorkerService:
    """Test double for the classification worker's service dependency.

    Inputs:
        name: Human-readable service label used in assertions and debugging.
        loop: Event loop that owns the worker stop event.
        stop_event: Worker stop event to set when the fake should end the loop.
        job: Optional job returned by ``claim_next_classification_job``.
        stop_after_claims: Optional claim count after which the fake stops the loop.

    Expected output:
        A service-like object recording claim and process calls.
    """

    def __init__(
        self,
        *,
        name: str,
        loop: asyncio.AbstractEventLoop,
        stop_event: asyncio.Event,
        job: SimpleNamespace | None = None,
        stop_after_claims: int | None = None,
    ) -> None:
        self.name = name
        self.loop = loop
        self.stop_event = stop_event
        self.job = job
        self.stop_after_claims = stop_after_claims
        self.claim_calls = 0
        self.processed_job_ids: list[str] = []

    def claim_next_classification_job(self, worker_id: str) -> SimpleNamespace | None:
        """Return the configured job once while recording the worker claim call.

        Inputs:
            worker_id: Unique worker id generated by the worker loop.

        Expected output:
            The configured fake job or ``None`` when no job is available.
        """

        del worker_id
        self.claim_calls += 1
        if self.stop_after_claims is not None and self.claim_calls >= self.stop_after_claims:
            self.loop.call_soon_threadsafe(self.stop_event.set)
        job = self.job
        self.job = None
        return job

    def process_claimed_classification_job(self, job_id: str) -> None:
        """Record the processed job id and stop the worker loop.

        Inputs:
            job_id: Claimed classification job id.

        Expected output:
            The fake service records ``job_id`` and asks the async worker to stop.
        """

        self.processed_job_ids.append(job_id)
        self.loop.call_soon_threadsafe(self.stop_event.set)


def test_classification_worker_reloads_service_between_empty_polls(monkeypatch) -> None:
    """Verify worker polling does not keep using a stale pre-refresh service."""

    async def run_worker() -> tuple[FakeClassificationWorkerService, FakeClassificationWorkerService]:
        """Run the worker until the fresh fake service processes its job or times out."""

        loop = asyncio.get_running_loop()
        stop_event = asyncio.Event()
        stale_service = FakeClassificationWorkerService(
            name="stale",
            loop=loop,
            stop_event=stop_event,
            stop_after_claims=2,
        )
        fresh_service = FakeClassificationWorkerService(
            name="fresh",
            loop=loop,
            stop_event=stop_event,
            job=SimpleNamespace(job_id="job-after-refresh", job_type="single"),
        )
        services = iter([stale_service, fresh_service])

        def get_service() -> FakeClassificationWorkerService:
            """Return the stale service for the first poll and fresh service afterwards."""

            try:
                return next(services)
            except StopIteration:
                return fresh_service

        monkeypatch.setattr(main_module, "get_metal_composition_service", get_service)
        settings = MetalCompositionSettings(
            workbook_path=Path("unused.xlsb"),
            api_env_path=Path(".env"),
            classification_job_worker_max_concurrency=1,
            classification_job_poll_interval_seconds=0.01,
        )
        await asyncio.wait_for(
            main_module._classification_job_worker_loop(stop_event, settings=settings),
            timeout=1.0,
        )
        return stale_service, fresh_service

    stale_service, fresh_service = asyncio.run(run_worker())

    assert stale_service.claim_calls == 1
    assert fresh_service.claim_calls >= 1
    assert fresh_service.processed_job_ids == ["job-after-refresh"]
