"""Request/response models for the extraction endpoints."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, StrictFloat, StrictInt


class ExtractionOptions(BaseModel):
    """Configuration mirrors the CLI flags in ``doc_extraction.main``."""

    llm_verify: bool = True
    llm_model: Optional[str] = None
    llm_min_confidence: float = 0.6
    top_k: int = 5
    merge_headers: bool = False
    output_name: Optional[str] = None

    embedding_model: Optional[str] = None
    show_preview: bool = False


class ExtractionJobSubmitResponse(BaseModel):
    """Response returned immediately after an extraction job is accepted.

    Inputs are generated by the job manager after upload validation. The output
    gives callers the stable URLs needed to poll job state and download the
    Excel workbook once processing succeeds.
    """

    job_id: str = Field(..., description="Stable identifier for the submitted extraction job")
    status: str = Field(..., description="Initial job status, normally QUEUED")
    status_url: str = Field(..., description="Relative URL for polling this job")
    download_url: str = Field(..., description="Relative URL for downloading the completed workbook")
    created_at: str = Field(..., description="UTC ISO-8601 timestamp for job creation")


class ExtractionJobStatusResponse(BaseModel):
    """Polling response for an extraction job.

    The response contains coarse progress, current status, previews and result
    metadata. Preview and result fields are populated only after successful
    completion; failed jobs expose their diagnostic messages in ``errors``.
    """

    job_id: str
    status: str
    progress: int
    stage: str
    message: str
    created_at: str
    updated_at: str
    started_at: Optional[str] = None
    finished_at: Optional[str] = None
    file_count: int
    llm_verify: bool
    top_k: int
    runtime_seconds: Optional[float] = None
    reference_data_version: Optional[str] = None
    output_filename: Optional[str] = None
    output_size: Optional[int] = None
    download_url: str
    headers_preview: List[Dict[str, Any]] = Field(default_factory=list)
    line_items_preview: List[Dict[str, Any]] = Field(default_factory=list)
    errors: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)


class JouleLineItem(BaseModel):
    """One commodity-code result rendered for a Joule user.

    Numeric document values remain numeric when detected. Missing values use the
    explicit ``Not detected`` text required by the conversational contract.

    Args:
        description: Extracted line-item description.
        net_amount: Detected numeric net amount or missing-value label.
        quantity: Detected numeric quantity or missing-value label.
        unit_price: Detected numeric unit price or missing-value label.
        ai_suggested_commodity_code: LLM-selected code, including ``UNSURE``.
        ai_confidence_score: Whole percentage string or missing-value label.
        ai_reasoning: LLM reasoning or retained fallback explanation.

    Returns:
        A validated seven-field line-item model for the public Joule response.
    """

    description: str
    net_amount: StrictInt | StrictFloat | str
    quantity: StrictInt | StrictFloat | str
    unit_price: StrictInt | StrictFloat | str
    ai_suggested_commodity_code: str
    ai_confidence_score: str
    ai_reasoning: str


class ExtractionResultPagination(BaseModel):
    """Navigation metadata for one fixed-size structured result page.

    Args:
        current_page: Current one-based page number.
        page_size: Fixed maximum number of line items per page.
        total_items: Total line items stored for the job.
        total_pages: Total number of available pages.
        previous_page: Previous page number, or ``None`` on the first page.
        next_page: Next page number, or ``None`` on the last page.

    Returns:
        Validated pagination metadata nested in a job result response.
    """

    current_page: int
    page_size: int
    total_items: int
    total_pages: int
    previous_page: Optional[int] = None
    next_page: Optional[int] = None


class ExtractionJobResultResponse(BaseModel):
    """One fixed-size page of structured Joule extraction results.

    Args:
        job_id: Stable extraction job identifier.
        status: Terminal job status, currently ``SUCCEEDED``.
        line_items: Up to 30 normalized Joule line items.
        pagination: Nested navigation metadata for the current page.

    Returns:
        The exact public result payload rendered by the API.
    """

    job_id: str
    status: str
    line_items: List[JouleLineItem] = Field(default_factory=list)
    pagination: ExtractionResultPagination


@dataclass(frozen=True, slots=True)
class JobResultFile:
    """Completed Excel artifact returned by the job download endpoint.

    Args:
        filename: File name presented to the browser.
        content_type: MIME type for the response.
        content: Raw workbook bytes stored in HANA.
    """

    filename: str
    content_type: str
    content: bytes
