"""
Customer Summary Service - Combined data for UI

Uses customer_summary_cache.parquet (generated by summary_aggregator)
"""

import pandas as pd
from typing import Dict, List, Optional
import logging

from .data_loader import load_from_parquet

logger = logging.getLogger(__name__)


def get_customer_summary(
    filters: Optional[Dict] = None,
    sort_by: str = "total_cogs",
    sort_order: str = "desc",
    limit: int = 100,
    exclude_unknown: bool = False
) -> Dict:
    """
    Get customer summary for UI table view

    Uses customer_summary_cache.parquet (generated by summary_aggregator)

    Args:
        filters: Optional filters dict with:
            - rfm_segment: str
            - sales_office: str
            - min_cogs: float
            - core_market: str
            - customer_group: str
        sort_by: Field to sort by (default: total_cogs)
        sort_order: 'asc' or 'desc'
        limit: Max customers to return
        exclude_unknown: If True, exclude customers with name="Unknown"

    Returns:
        Dict with:
        - total_customers: int
        - filtered_customers: int
        - summary_stats: dict with aggregates
        - customers: list of customer dicts
    """
    logger.info(f"Getting customer summary: sort_by={sort_by}, limit={limit}, exclude_unknown={exclude_unknown}")

    # Load from cache
    try:
        cache = load_from_parquet('customer_summary_cache.parquet')
    except Exception as e:
        logger.error(f"Could not load cache: {e}")
        raise Exception(f"Customer summary cache not available: {e}")

    df = cache.copy()

    logger.info(f"Loaded cache: {len(df)} customers")

    # Apply filters
    total_customers = len(df)

    # Exclude Unknown names if requested
    if exclude_unknown:
        df = df[df['customer_name'] != 'Unknown']
        logger.info(f"After exclude_unknown: {len(df)} customers")

    if filters:
        for key, value in filters.items():
            if value is None:
                continue

            if key == 'rfm_segment' and key in df.columns:
                df = df[df[key] == value]
            elif key == 'sales_office' and key in df.columns:
                df = df[df[key].astype(str) == str(value)]
            elif key == 'min_cogs':
                df = df[df['total_cogs'] >= float(value)]
            elif key == 'core_market' and key in df.columns:
                df = df[df[key] == value]
            elif key == 'customer_group' and key in df.columns:
                df = df[df[key] == value]

    filtered_customers = len(df)
    logger.info(f"After filters: {filtered_customers} customers")

    # Calculate summary stats
    summary_stats = {
        'total_cogs': float(df['total_cogs'].sum()) if len(df) > 0 else 0,
        'total_savings': float(df['total_savings'].sum()) if len(df) > 0 else 0,
        'total_potential': float(df['potential_value_estimate'].sum()) if len(df) > 0 else 0,
        'total_potential_full_bundle': float(df['potential_value_full_bundle'].sum()) if len(df) > 0 and 'potential_value_full_bundle' in df.columns else 0,
        'customers_with_savings': int((df['total_savings'] > 0).sum()),
        'customers_with_potential': int((df['potential_value_estimate'] > 0).sum()),
        'high_value_customers': int((df['total_cogs'] > 100000).sum()),
        'champions_count': int((df['rfm_segment'] == 'Champions').sum()) if 'Champions' in df['rfm_segment'].values else 0,
        'at_risk_count': int((df['rfm_segment'] == 'At Risk').sum()) if 'At Risk' in df['rfm_segment'].values else 0
    }

    # Sort
    ascending = (sort_order == 'asc')
    if sort_by in df.columns:
        df = df.sort_values(by=sort_by, ascending=ascending)

    # Limit
    df = df.head(limit)

    # Convert to list of dicts
    customers = []
    for _, row in df.iterrows():
        customers.append({
            'customer_id': str(row['customer_id']),
            'customer_name': str(row.get('customer_name', 'Unknown')),
            'sales_office': str(row.get('sales_office', '')) if pd.notna(row.get('sales_office')) else '',
            'core_market': str(row.get('core_market', '')) if pd.notna(row.get('core_market')) else '',
            'customer_group': str(row.get('customer_group', '')) if pd.notna(row.get('customer_group')) else '',
            'pl_type': str(row.get('pl_type', '')) if pd.notna(row.get('pl_type')) else '',
            'rfm_segment': str(row.get('rfm_segment', 'N/A')),
            'total_cogs': float(row['total_cogs']),
            'total_savings': float(row['total_savings']),
            'savings_percent': float(row['savings_percent']) if pd.notna(row.get('savings_percent')) else 0.0,
            'coverage_percent': float(row['coverage_percent']) if pd.notna(row.get('coverage_percent')) else 0.0,
            'savings_percent_normalized': float(row['savings_percent_normalized']) if pd.notna(row.get('savings_percent_normalized')) else 0.0,
            'cogs_covered': float(row['cogs_covered']) if pd.notna(row.get('cogs_covered')) else 0.0,
            'cogs_not_covered': float(row['cogs_not_covered']) if pd.notna(row.get('cogs_not_covered')) else 0.0,
            'missing_spas_count': int(row['missing_spas_count']) if pd.notna(row.get('missing_spas_count')) else 0,
            'potential_value_estimate': float(row['potential_value_estimate']) if pd.notna(row.get('potential_value_estimate')) else 0.0,
            'potential_value_full_bundle': float(row['potential_value_full_bundle']) if pd.notna(row.get('potential_value_full_bundle')) else 0.0,
            'potential_is_estimate': bool(row.get('potential_is_estimate', True)),
            'potential_estimate_materials_count': int(row['potential_estimate_materials_count']) if pd.notna(row.get('potential_estimate_materials_count')) else 0,
            'potential_estimate_cogs_basis': float(row['potential_estimate_cogs_basis']) if pd.notna(row.get('potential_estimate_cogs_basis')) else 0.0,
            'potential_estimate_note': str(row.get('potential_estimate_note', '')) if pd.notna(row.get('potential_estimate_note')) else ''
        })

    return {
        'total_customers': total_customers,
        'filtered_customers': filtered_customers,
        'summary_stats': summary_stats,
        'customers': customers
    }


def get_customer_summary_stats() -> Dict:
    """
    Get overall summary statistics

    Returns:
        Dict with high-level stats
    """
    try:
        cache = load_from_parquet('customer_summary_cache.parquet')

        stats = {
            'total_customers': len(cache),
            'total_cogs': float(cache['total_cogs'].sum()),
            'total_savings': float(cache['total_savings'].sum()),
            'total_potential': float(cache['potential_value_estimate'].sum()),
            'total_potential_full_bundle': float(cache['potential_value_full_bundle'].sum()) if 'potential_value_full_bundle' in cache.columns else 0,
            'customers_with_savings': int((cache['total_savings'] > 0).sum()),
            'customers_with_potential': int((cache['potential_value_estimate'] > 0).sum()),
            'avg_savings_per_customer': float(cache[cache['total_savings'] > 0]['total_savings'].mean()) if len(cache[cache['total_savings'] > 0]) > 0 else 0,
            'rfm_distribution': cache['rfm_segment'].value_counts().to_dict()
        }

        return stats
    except Exception as e:
        logger.error(f"Could not load cache for stats: {e}")
        raise Exception(f"Customer summary cache not available: {e}")
